navbarPage(
  theme = shinytheme("cosmo"),
  collapsible = FALSE,
  fluid = TRUE,
  "Sentiment Analysis of Coffee Tweets",
  id ="main", 
  tabPanel("About", p("What can this app be used for?"),
           p(  "* Our application can be used to determine and compare the sentiments of tweets about different words associated with coffee, including coffee shops around the world."),
           
           p("How can we use this app?"),
           
           p("* View tweets including a word"),
           
           p("* View Word Clouds generated by tweets including a word"),
           
           p("*"),
           
           p("*")),
  tabPanel("Table",
    sidebarLayout(
      sidebarPanel(
        conditionalPanel(
          'input.dataset == "coffee"',
          helpText('Tweets including "coffee"')
               ),
        conditionalPanel(
          'input.dataset == "starbucks"',
          helpText('Tweets including "starbucks"')
        ),
        conditionalPanel(
          'input.dataset == "dunkin"',
          helpText('Tweets including "dunkin"')
        ),
        conditionalPanel(
          'input.dataset == "shiru"',
          helpText('Tweets including "shiru"')
        )
      ),
      mainPanel(
        tabsetPanel(
          id = 'dataset',
          tabPanel("coffee", DT::dataTableOutput("table1")),
          tabPanel("starbucks", DT::dataTableOutput("table2")),
          tabPanel("dunkin", DT::dataTableOutput("table3")),
          tabPanel("shiru", DT::dataTableOutput("table4"))
        )
      )
    )
  ),
  tabPanel("Graphs",  tabsetPanel(
    tabPanel("Word Cloud", 
             fluidPage(
      # Application title
               titlePanel("Word Cloud"),
               sidebarLayout(
        # Sidebar with a slider and selection inputs
        sidebarPanel(
          selectInput("selection1", "Choose a Word:", choices = c("coffee","starbucks", "dunkin", "shiru")),
          hr(),
          sliderInput("max",
                      "Maximum Number of Words:",
                      min = 1,  max = 50,  value = 50)
        ),
        
        # Show Word Cloud
        mainPanel(
          plotOutput("plot1")
        )
      )
    )),
    tabPanel("Bar Graph",
             fluidPage(
               #Application title
               titlePanel("Bar Graph"),
               sidebarLayout(
                 #Sidebar with a slide and selection inputs
                 sidebarPanel(
                   selectInput("word", "Choose a Word:", choices = c("coffee","starbucks", "dunkin", "shiru")),
                   hr()
                 ),
                 # Show Bar Plot
                 mainPanel (
                   plotOutput("plot2")
                 )
               )
             )),
    tabPanel("xx")
    )
  )
)